# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def EvnFiboSum(limit, cond):
    sum = 0
    t1 = 1
    t2 = 2
    i = t1

    while i <= limit:
        t3 = t1 + t2
        if t3 > limit:
            break
        if cond == 'e':
            x = 2  
            if t3 % 2 == 0:
                sum += t3
        if cond == 'o':
            x = 1
            if t3 % 2 != 0:
                sum+=t3
                
        t1 = t2
        t2 = t3
        i += 1
    
    sum+=x
    return sum

print(EvnFiboSum(4000000,'e'))
